coverage:
  status:
    project:
      default:
        target: 80%

  # Include specific files or directories
  include:
    - "pyccea/utils/datasets.py"
    - "pyccea/coevolution/*"

  # Define thresholds and precision
  coverage:
    precision: 2
    round: down
