coverage:
  status:
    project:
      default:
        target: 80%

  include:
    - "pyccea/utils/datasets.py"
    - "pyccea/coevolution/*"

  exclude:
    - "*/tests/*"

  coverage:
    precision: 2
    round: down
