name: Build and deploy documentation

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme numpydoc

      - name: Generate module-level .rst files
        run: |
          sphinx-apidoc -o docs/source/pages pyccea \
            --force \
            --separate \
            --module-first \
            --implicit-namespaces

      - name: Build Sphinx docs
        run: |
          python -m sphinx -b html docs/source docs/_build/html

      - name: Check built docs files
        run: ls -l docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages
