name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov codecov

      - name: Run tests with coverage
        run: pytest --cov=pyccea/utils --cov=pyccea/coevolution --cov=pyccea/cooperation

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
